apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-demo-config
  namespace: krakenddemo-namespace
data:
  krakend.json: |
           {

             "$schema" : "https://www.krakend.io/schema/krakend.json",

             "version" : 3,

             "name" : "Testing",

             "port" : 8082,

             "host" : [ "http://localhost" ],

             "timeout" : "3000ms",

             "cache_ttl" : "300s",

             "debug_endpoint" : false,

             "endpoints" : [ {

               "endpoint" : "/context4/end2",

               "backend" : [ {

                 "host" : [ "https://jsonplaceholder.typicode.com" ],

                 "url_pattern" : "/posts",

                 "is_collection" : true,

                 "encoding" : "json",

                 "method" : "GET"

               }, {

                 "host" : [ "https://jsonplaceholder.typicode.com" ],

                 "url_pattern" : "/users",

                 "extra_config" : {

                   "plugin/req-resp-modifier" : {

                     "name" : [ "response-schema-validator" ],

                     "response-schema-validator" : {

                       "error" : {

                         "body" : "errmsg",

                         "status" : 500

                       },

                       "schema" : {

                         "a" : "b"

                       }

                     }

                   },

                   "proxy" : { }

                 },

                 "method" : "GET",

                 "disable_host_sanitize" : true

               } ],

               

               "output_encoding" : "json",

               "method" : "GET"

             } ],

             "extra_config" : { }

           }
